oamg/rhc-worker-script

.github/workflows/release.yml, Makefile, README.md, go.mod, packaging/rhc-bash-worker.spec, python/mqtt_publish.py, src/logger.go, src/main.go, src/util.go
Since the worker could be potentially used for both Conversions and Migrations, the worker and its references were renamed to be generic.
=> Rename project references to be generic

src/server.go, src/util.go
HMS-2042
Our own metadata currently contain only content type. If needed in future, the initial structure `ourMetadata` in `constructMetadata` can be extended.
=> Merge received message metadata with ours

.gitignore, README.md, development/nginx/command, development/nginx/data/yaml-file, development/nginx/worker.conf, development/podman-compose.yml, development/python/mqtt_publish.py, go.sum, src/logger.go, src/logger_test.go, src/main.go, src/runner.go, src/runner_test.go, src/server.go, src/server_test.go, src/util.go, src/util_test.go
[HMS-1994](https://issues.redhat.com/browse/HMS-1994)
- Done similarly like for [rhc-worker-playbook ](https://github.com/RedHatInsights/rhc-worker-playbook/blob/main/rhc_worker_playbook/server.py#L185)
=> Parse minimal yaml instead of raw bash script

README.md, src/main.go, src/runner.go, src/runner_test.go, src/server.go, src/util.go, src/util_test.go
Fixes #41 
Yaml config at `'/etc/rhc/workers/rhc-worker-bash.yml'` can now change behavior of worker, this is similar to rhc-worker-playbook (they have [toml config](https://github.com/RedHatInsights/rhc-worker-playbook/blob/main/rhc-worker-playbook.toml), but since we are already using yaml module our config is also yaml)
=> Add option to create config for rhc-worker-bash

.github/workflows/release.yml
Reverts oamg/rhc-worker-bash#45
We need to keep the go-cross-build as 1.0.2 since there is a problem with the latest release introduced in v1.1.0. And as weird as it seems, v1.0.2 was the latest release for this action.
=> Revert "Bump thatisuday/go-cross-build from 1.0.2 to 1.1.0"

src/runner.go, src/server.go, src/server_test.go
Taken from #42 , just refactor with tests
=> Refactor server.go file and add tests

src/runner.go, src/runner_test.go
[HMS-2240](https://issues.redhat.com/browse/HMS-2240)
- the test verifies that same variables can be set for two different commands with different values
=> Use separate environment for every executed command

src/main.go
This log was placed on main during the early stages of development to figure out if the variables was being set properly, since that part is mostly stable, we can remove this log once for all.
=> Remove unnecessary logging

src/logger.go, src/logger_test.go, src/main.go, src/util.go
SOS Report needs a special file in the /etc/sos.extras.d/ folder to be able to collect the log files for the worker. Since it won't have a special plugin in sosreport due to RHEL 7 being in maintenance mode, we will be using this strategy to make sure that sosreport will be able to collect our logs.
=> Add setup for sos report

.github/workflows/release.yml, .packit.yaml, CONTRIBUTING.md, Makefile, README.md, development/nginx/data/example_bash.yml, development/nginx/data/example_python.yml, development/python/mqtt_publish.py, go.mod, packaging/rhc-worker-script.spec, packaging/rhc-worker.spec, rhc-worker.yml, src/fixtures_test.go, src/logger.go, src/main.go, src/runner.go, src/server.go, src/util.go, src/util_test.go
The idea behind this commit is to make the worker even more generic, not only being able to execute bash scripts, but, let the user decide which type of script it will be executed, by defining a `interpreter` key in the partial yaml playbook, which will tell the worker what to execute.
Changes included in this commit:
* Rename every reference from rhc-worker-bash to rhc-worker
* Added the `interpreter` key to be parsed in the incoming playbook 
** Use the `interpreter` key instead of hardcoding the /bin/bash path
for the command execution
* Updated the references in the project to build using the new name
=> Update the worker to make it more generic

Makefile, development/nginx/data/example_bash.yml, development/nginx/data/example_python.yml
The Makefile was using old targets name to build the worker.
=> Update Makefile and playbook examples

packaging/rhc-worker-script.spec
This commit changes how the specfile generate the binary name as RHC needs that the binary ends with the `-worker` termination.
=> Update specfile binary name generation

packaging/rhc-worker-script.spec
The specfile was using the release archive, which contains only source code, not the vendored dependencies we need. This change is modifying the specfile to pull the changes from the correct place
=> Update Source0 URL in specfile

.github/workflows/verify.yml, .pre-commit-config.yaml
Trying to fix the pre-commit. I am still not convinced that our config is the issue.
=> Move golangci-lint from pre-commit to CI

.pre-commit-config.yaml
gitleaks installed via go requires newer version (1.17) than our worker does (1.16)
=> Change gitleaks to use docker

README.md, packaging/rhc-worker-script.spec
[HMS-2572](https://issues.redhat.com/browse/HMS-2572)
Minimal version of a configuration file is included in the specfile now and it will be generated at the /etc/rhc/workers/ folder.
=> Update specfile to include config file

src/server.go, src/util.go
- Removed one log from server.go because same log is called in `sendDataToDispatcher`
- Added info log when default values for config are used.
=> Improve logging when config file can't be used and default values are used instead

src/main.go
We were losing the first Infoln call because we were setting up the logging after that.
=> Move the logging init to be before anything else

src/main.go, src/runner.go
If the user specify that the insights gpg check should be disabled, we should do nothing and execute the script anyway, as there is no gpg check to be performed. Otherwise, if the gpg check is still enabled, we call insights-client to verify the signature.
If there is no need to validate the gpg signature, we should not call insights-client for it.
[HMS-2647](https://issues.redhat.com/browse/HMS-2647)
=> Improve logging when insights_core_gpg_check is disabled

README.md, packaging/rhc-worker-script.spec, rhc-worker-script.yml, src/runner.go, src/runner_test.go, src/server_test.go, src/util.go, src/util_test.go
Fixes: https://github.com/oamg/rhc-worker-script/issues/103
- Workaround would be to remove gpg verification option, the problem is present only when `--no-gpg` option is specified but we still want to verify yaml
:thinking: Does it make sense to allow `insights_gpg_check: false` and `verify_yaml: true`, if we don't verify insights-client authenticity how can we trust verification results?
But it seems that the playbook worker [does the same](https://github.com/RedHatInsights/rhc-worker-playbook/blob/0.1.8/rhc_worker_playbook/server.py#L181) (I mean that is why I wrote it  same in our worker), why..
the problematic exception in insight-core is [here](https://github.com/RedHatInsights/insights-core/blob/insights-core-3.2.1/insights/client/apps/ansible/playbook_verifier/contrib/gnupg.py#L159 …
=> Remove insights_core_gpg_check from worker config

development/nginx/data/convert2rhel.yml, rhc-worker-script.yml, src/runner.go
Use case: problem in conversion script when script exited with 1 but we had to manually reproduce the situation to see which part of code was problematic
Related to https://github.com/oamg/convert2rhel-worker-scripts/pull/46
=> When script fails with exit code 1 we want to see the reason in logs

Makefile, packaging/rhc-worker-script.spec
* Update SERVED_FILENAME in Makefile by @r0x0d in https://github.com/oamg/rhc-worker-script/pull/98
* Bump actions/checkout from 3 to 4 by @dependabot in https://github.com/oamg/rhc-worker-script/pull/99
* Bump github.com/google/uuid from 1.3.1 to 1.4.0 by @dependabot in https://github.com/oamg/rhc-worker-script/pull/102
* Fix grpc to newest v1.59.x version by @andywaltlova in https://github.com/oamg/rhc-worker-script/pull/101
* Remove insights_core_gpg_check from worker config by @andywaltlova in https://github.com/oamg/rhc-worker-script/pull/104
* [pre-commit.ci] pre-commit autoupdate by @pre-commit-ci in https://github.com/oamg/rhc-worker-script/pull/105
* When script fails with exit code 1 we want to see the reason in logs by @andywaltlova in …
=> Release v0.6 Gojira

README.md
The example script links all end in the .yaml extension but the actual scripts have the extension .yml. This change fixes the links so that they no longer lead to a 404 page.
=> Fix broken example script links

rhc-worker-script.yml, src/runner.go, src/runner_test.go, src/server_test.go, src/util.go, src/util_test.go
[HMS-3837](https://issues.redhat.com/browse/HMS-3837)
TBD, for future https://github.com/oamg/convert2rhel-worker-scripts/issues/49
=> Pass log level to executed script for more granular logging possibility

development/podman-compose.yml
The old repository in quay.io got archived for insights-ingress. This is the new one.
=> Update insights-ingress docker image

packaging/rhc-worker-script.spec
We missed the changelog for bumping the version of golang-protobuf in the 0.7 release.
=> Include missing changelog for version 0.7

packaging/rhc-worker-script.spec
Since we are building with a new buildroot that contains go 1.21, we don't require the scl workarounds anymore. We can just use plain golang in the BuildRequires and the normal make build.
=> Remove SCL conditions from specfile
